config/routes.rb
Rails.application.routes.draw do
  root :to => "welcome#index" 

 resources :registrations

  get 'welcome/index'
  get 'about/index'
  get '/registrations/' => 'registrations#index'

end

app/models/registration.rb
class Registration < ActiveRecord::Base
	validates :last, :first, :address, :city, :state, :postal, :country, :login, presence:true	
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
  before_action :set_registration, only: [:show, :edit, :update, :destroy]

  # GET /registrations
  # GET /registrations.json
  def index
    @registrations = Registration.all
  end

  # GET /registrations/1
  # GET /registrations/1.json
  def show
  end

  # GET /registrations/new
  def new
    @registration = Registration.new
  end

  # GET /registrations/1/edit
  def edit
  end

  # POST /registrations
  # POST /registrations.json
  def create
    @registration = Registration.new(registration_params)

    respond_to do |format|
      if @registration.save
        format.html { redirect_to @registration, notice: 'Registration was successfully created.' }
        format.json { render :show, status: :created, location: @registration }
      else
        format.html { render :new }
        format.json { render json: @registration.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /registrations/1
  # PATCH/PUT /registrations/1.json
  def update
    respond_to do |format|
      if @registration.update(registration_params)
        format.html { redirect_to @registration, notice: 'Registration was successfully updated.' }
        format.json { render :show, status: :ok, location: @registration }
      else
        format.html { render :edit }
        format.json { render json: @registration.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /registrations/1
  # DELETE /registrations/1.json
  def destroy
    @registration.destroy
    respond_to do |format|
      format.html { redirect_to registrations_url, notice: 'Registration was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_registration
      @registration = Registration.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def registration_params
      params.require(:registration).permit(:last, :first, :address, :city, :state, :country, :postal, :login)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/states_helper.rb
module StatesHelper

def us_states
    [
      ['Please select'],
      ['Alabama', 'AL'],
      ['Alaska', 'AK'],
      ['Arizona', 'AZ'],
      ['Arkansas', 'AR'],
      ['California', 'CA'],
      ['Colorado', 'CO'],
      ['Connecticut', 'CT'],
      ['Delaware', 'DE'],
      ['District of Columbia', 'DC'],
      ['Florida', 'FL'],
      ['Georgia', 'GA'],
      ['Hawaii', 'HI'],
      ['Idaho', 'ID'],
      ['Illinois', 'IL'],
      ['Indiana', 'IN'],
      ['Iowa', 'IA'],
      ['Kansas', 'KS'],
      ['Kentucky', 'KY'],
      ['Louisiana', 'LA'],
      ['Maine', 'ME'],
      ['Maryland', 'MD'],
      ['Massachusetts', 'MA'],
      ['Michigan', 'MI'],
      ['Minnesota', 'MN'],
      ['Mississippi', 'MS'],
      ['Missouri', 'MO'],
      ['Montana', 'MT'],
      ['Nebraska', 'NE'],
      ['Nevada', 'NV'],
      ['New Hampshire', 'NH'],
      ['New Jersey', 'NJ'],
      ['New Mexico', 'NM'],
      ['New York', 'NY'],
      ['North Carolina', 'NC'],
      ['North Dakota', 'ND'],
      ['Ohio', 'OH'],
      ['Oklahoma', 'OK'],
      ['Oregon', 'OR'],
      ['Pennsylvania', 'PA'],
      ['Puerto Rico', 'PR'],
      ['Rhode Island', 'RI'],
      ['South Carolina', 'SC'],
      ['South Dakota', 'SD'],
      ['Tennessee', 'TN'],
      ['Texas', 'TX'],
      ['Utah', 'UT'],
      ['Vermont', 'VT'],
      ['Virginia', 'VA'],
      ['Washington', 'WA'],
      ['West Virginia', 'WV'],
      ['Wisconsin', 'WI'],
      ['Wyoming', 'WY']
    ]
end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/about/index.html.erb
<h1>About#index</h1>
<p>Find me in app/views/about/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MG Site</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="welcome#index">
                    <img src="/assets/mg.jpg" alt="Logo">
                </a>
            </div>
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li>
                        <%= link_to "About", about_index_path %>
                    </li>
                    <li>
                        <%= link_to "Registration", registrations_path %>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

<body>

<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

    <title>MG Site</title>

    <link href="/assets/application.css" rel="stylesheet">

</head>

<body>

    <div class="container">

        <div class="row">
            <div class="col-md-8">
                <img class="img-responsive img-rounded" src="/assets/road.jpg". alt="Highway Road">
            </div>
            <div class="col-md-4">
                <h1>MG United</h1>
                <p>Finally a site that brings all of us affected by Myasthenia Gravis together. Join us in this difficult journey that lays ahead. Walking together is better than walking alone.</p>
                <a class="btn btn-primary btn-lg" href="#">Register or Sign in</a>
            </div>
        </div>

        <hr>

        <div class="row">
            <div class="col-lg-12">
                <div class="well text-center">
                    Bringing Myasthenia patients together in one location! Come stay united with us!
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-4">
                <h2>About</h2>
                <p>This site was created to bring together all stages of Myasthenia Gravis together. We are all in need of support and knowing that we are not alone during our low points and high points.</p>
                <a class="btn btn-default" href="#">More Info</a>
            </div>
            <div class="col-md-4">
                <h2>Resources</h2>
                <p>Newly diagnosed and have no idea what you have exactly? He we strive to collaborate with new and experienced MGers to provide as much information as possible. We strive to create credible information on all fronts.</p>
                <a class="btn btn-default" href="#">More Info</a>
            </div>
            <div class="col-md-4">
                <h2>Community</h2>
                <p>We have created a community of all MG patients where we can support and give personal experiences. It is important to speak with new and experienced MGers because Myasthenia Gravis is not a popular disease.  We all need to stay connected with each other!</p>
                <a class="btn btn-default" href="#">More Info</a>
            </div>
        </div>

        <footer>
            <div class="row">
                <div class="col-lg-12">
                    <p>Copyright &copy; MG United 2015</p>
                </div>
            </div>
        </footer>

    </div>

</body>

</html>